# Generated by Django 4.2 on 2025-09-19 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='모델명')),
                ('model_type', models.CharField(choices=[('local', '로컬'), ('external', '외부')], max_length=20, verbose_name='모델 타입')),
                ('model_provider', models.CharField(choices=[('OpenAI', 'OpenAI'), ('Google', 'Google'), ('Anthropic', 'Anthropic'), ('HuggingFace', 'HuggingFace'), ('Ollama', 'Ollama'), ('Other', '기타')], max_length=50, verbose_name='모델 제공자')),
                ('model_api_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='API 키')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'LLM 모델',
                'verbose_name_plural': 'LLM 모델들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_settings', models.JSONField(blank=True, null=True, verbose_name='업로드 설정')),
                ('ask_settings', models.JSONField(blank=True, null=True, verbose_name='질문 설정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 설정',
                'verbose_name_plural': '사용자 설정들',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='파일')),
                ('prompt_text', models.TextField(verbose_name='프롬프트 텍스트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '문서',
                'verbose_name_plural': '문서들',
                'ordering': ['-created_at'],
            },
        ),
    ]
