# Generated by Django 4.2 on 2025-09-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_llmlist_usersetting_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
