# Generated by Django 4.2 on 2025-09-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_document_chunk_overlap_document_chunk_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='chunk_overlap',
        ),
        migrations.RemoveField(
            model_name='document',
            name='chunk_size',
        ),
        migrations.RemoveField(
            model_name='document',
            name='selected_llm',
        ),
    ]
