# Generated by Django 4.2 on 2025-09-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_document_chunk_overlap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunk_overlap',
            field=models.IntegerField(default=200, verbose_name='청크 겹침 글자수'),
        ),
        migrations.AddField(
            model_name='document',
            name='chunk_size',
            field=models.IntegerField(default=1000, verbose_name='청크 글자수'),
        ),
        migrations.AddField(
            model_name='document',
            name='selected_llm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.llmlist', verbose_name='선택된 LLM 모델'),
        ),
    ]
