# Generated by Django 4.2 on 2025-09-20 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_document_chunk_overlap_document_chunk_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', '사용자'), ('assistant', 'AI 어시스턴트'), ('system', '시스템')], max_length=20, verbose_name='메시지 타입')),
                ('req_content', models.TextField(verbose_name='요청 내용')),
                ('res_content', models.TextField(verbose_name='응답 내용')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='사용된 토큰 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('llm_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.llmlist', verbose_name='사용된 LLM 모델')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지들',
                'ordering': ['created_at'],
            },
        ),
    ]
