# Generated by Django 4.2 on 2025-09-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
