# Generated by Django 4.2 on 2025-09-20 12:30

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=home.models.user_directory_path, verbose_name='파일'),
        ),
    ]
