# Generated by Django 4.2 on 2025-09-20 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='referenced_chunks',
            field=models.JSONField(blank=True, default=list, verbose_name='참조된 청크들'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='search_scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='검색 점수들'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='selected_documents',
            field=models.ManyToManyField(blank=True, to='home.document', verbose_name='선택된 문서들'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='처리 완료 여부'),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(default='pending', max_length=50, verbose_name='처리 상태'),
        ),
        migrations.AddField(
            model_name='document',
            name='total_chunks',
            field=models.IntegerField(default=0, verbose_name='총 청크 수'),
        ),
        migrations.CreateModel(
            name='DocumentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='세션 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('selected_documents', models.ManyToManyField(related_name='selections', to='home.document', verbose_name='선택된 문서들')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '문서 선택',
                'verbose_name_plural': '문서 선택들',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(verbose_name='청크 순서')),
                ('content', models.TextField(verbose_name='청크 내용')),
                ('metadata', models.JSONField(default=dict, verbose_name='메타데이터')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='임베딩 벡터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='home.document', verbose_name='문서')),
            ],
            options={
                'verbose_name': '문서 청크',
                'verbose_name_plural': '문서 청크들',
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
